# Generated by Django 5.0.8 on 2024-08-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblBodyguard',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('experience', models.IntegerField(blank=True, db_column='Experience', null=True)),
                ('gender', models.SmallIntegerField(blank=True, db_column='Gender', null=True)),
                ('dateofbirth', models.DateField(blank=True, db_column='DateOfBirth', null=True)),
                ('hiredate', models.DateField(blank=True, db_column='HireDate', null=True)),
                ('education', models.TextField(blank=True, db_column='Education', null=True)),
                ('salary', models.DecimalField(blank=True, db_column='Salary', decimal_places=0, max_digits=18, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
            ],
            options={
                'db_table': 'tbl_bodyguard',
            },
        ),
        migrations.CreateModel(
            name='TblCertificate',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=500, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('link', models.CharField(blank=True, db_column='Link', max_length=500, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
            ],
            options={
                'db_table': 'tbl_certificate',
            },
        ),
        migrations.CreateModel(
            name='TblContract',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('registrationid', models.IntegerField(blank=True, db_column='RegistrationID', null=True)),
                ('customername', models.CharField(blank=True, db_column='CustomerName', max_length=255, null=True)),
                ('customerphone', models.CharField(blank=True, db_column='CustomerPhone', max_length=20, null=True)),
                ('customeremail', models.CharField(blank=True, db_column='CustomerEmail', max_length=255, null=True)),
                ('customeraddress', models.CharField(blank=True, db_column='CustomerAddress', max_length=500, null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=6, null=True)),
                ('linkcontract', models.CharField(blank=True, db_column='LinkContract', max_length=255, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
            ],
            options={
                'db_table': 'tbl_contract',
            },
        ),
        migrations.CreateModel(
            name='TblCustomer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=200, null=True)),
                ('password', models.CharField(blank=True, db_column='PASSWORD', max_length=500, null=True)),
                ('createat', models.DateTimeField(blank=True, db_column='CreateAt', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
            ],
            options={
                'db_table': 'tbl_customer',
            },
        ),
        migrations.CreateModel(
            name='TblEquipment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('unit', models.CharField(blank=True, db_column='Unit', max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
            ],
            options={
                'db_table': 'tbl_equipment',
            },
        ),
        migrations.CreateModel(
            name='TblLectures',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=500, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=500, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
            ],
            options={
                'db_table': 'tbl_lectures',
            },
        ),
        migrations.CreateModel(
            name='TblRole',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_role',
            },
        ),
        migrations.CreateModel(
            name='TblService',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=0, max_digits=18, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
            ],
            options={
                'db_table': 'tbl_service',
            },
        ),
        migrations.CreateModel(
            name='TblTraining',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=500, null=True)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('status', models.BooleanField(blank=True, db_column='Status', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('lecturesid', models.ForeignKey(blank=True, db_column='LecturesID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tbllectures')),
            ],
            options={
                'db_table': 'tbl_training',
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'unique_together': {('principal_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TblBackgound',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=500, null=True)),
                ('story', models.TextField(blank=True, db_column='Story', null=True)),
                ('evaluate', models.CharField(blank=True, db_column='Evaluate', max_length=5, null=True)),
                ('link', models.CharField(blank=True, db_column='Link', max_length=255, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('guardid', models.ForeignKey(blank=True, db_column='GuardID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblbodyguard')),
            ],
            options={
                'db_table': 'tbl_backgound',
            },
        ),
        migrations.CreateModel(
            name='TblContractDetail',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('link', models.CharField(blank=True, db_column='Link', max_length=255, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('contractid', models.ForeignKey(blank=True, db_column='ContractID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblcontract')),
            ],
            options={
                'db_table': 'tbl_contract_detail',
            },
        ),
        migrations.CreateModel(
            name='TblDayoff',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('leavestarttime', models.DateTimeField(blank=True, db_column='LeaveStartTime', null=True)),
                ('numberofdays', models.IntegerField(blank=True, db_column='NumberOfDays', null=True)),
                ('isapproved', models.CharField(blank=True, db_column='IsApproved', max_length=10, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('approverid', models.ForeignKey(blank=True, db_column='ApproverID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbldayoff_approverid_set', to='bgapp.tblbodyguard')),
                ('guardid', models.ForeignKey(blank=True, db_column='GuardID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblbodyguard')),
            ],
            options={
                'db_table': 'tbl_dayoff',
            },
        ),
        migrations.CreateModel(
            name='TblEmergencyContact',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('note', models.TextField(blank=True, db_column='NOTE', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('contractid', models.ForeignKey(blank=True, db_column='ContractID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblcontract')),
            ],
            options={
                'db_table': 'tbl_emergency_contact',
            },
        ),
        migrations.CreateModel(
            name='TblFeedback',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, db_column='MESSAGE', null=True)),
                ('evaluate', models.CharField(blank=True, db_column='Evaluate', max_length=5, null=True)),
                ('responded', models.BooleanField(blank=True, db_column='Responded', null=True)),
                ('createat', models.DateTimeField(blank=True, db_column='CreateAt', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('contractid', models.ForeignKey(blank=True, db_column='ContractID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblcontract')),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
        migrations.CreateModel(
            name='TblPayment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=0, max_digits=18, null=True)),
                ('paymentstatus', models.BooleanField(blank=True, db_column='PaymentStatus', null=True)),
                ('details', models.TextField(blank=True, db_column='Details', null=True)),
                ('createat', models.DateTimeField(blank=True, db_column='CreateAt', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('contractid', models.ForeignKey(blank=True, db_column='ContractID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblcontract')),
            ],
            options={
                'db_table': 'tbl_Payment',
            },
        ),
        migrations.CreateModel(
            name='TblPaymentTransaction',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=0, max_digits=18, null=True)),
                ('transactiondate', models.DateField(blank=True, db_column='TRANSACTIONDate', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('createat', models.DateTimeField(blank=True, db_column='CreateAt', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('billid', models.ForeignKey(blank=True, db_column='BillID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblpayment')),
            ],
            options={
                'db_table': 'tbl_payment_transaction',
            },
        ),
        migrations.CreateModel(
            name='TblRegistration',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('requirement', models.TextField(blank=True, db_column='Requirement', null=True)),
                ('manquantity', models.IntegerField(blank=True, db_column='ManQuantity', null=True)),
                ('womanquantity', models.IntegerField(blank=True, db_column='WomanQuantity', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('interview_time', models.DateTimeField(blank=True, db_column='Interview_time', null=True)),
                ('interview_location', models.CharField(blank=True, db_column='Interview_Location', max_length=255, null=True)),
                ('createat', models.DateTimeField(blank=True, db_column='CreateAt', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('customerid', models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblcustomer')),
                ('serivceid', models.ForeignKey(blank=True, db_column='SerivceID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblservice')),
            ],
            options={
                'db_table': 'tbl_registration',
            },
        ),
        migrations.AddField(
            model_name='tblcontract',
            name='serivceid',
            field=models.ForeignKey(blank=True, db_column='SerivceID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblservice'),
        ),
        migrations.CreateModel(
            name='TblTimekeeping',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('timein', models.DateTimeField(blank=True, db_column='TimeIn', null=True)),
                ('timeout', models.DateTimeField(blank=True, db_column='TimeOut', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('guardid', models.ForeignKey(blank=True, db_column='GuardID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblbodyguard')),
                ('supvisorid', models.ForeignKey(blank=True, db_column='SupvisorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbltimekeeping_supvisorid_set', to='bgapp.tblbodyguard')),
            ],
            options={
                'db_table': 'tbl_timekeeping',
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_column='PASSWORD', max_length=500, null=True)),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=255, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('roleid', models.ForeignKey(blank=True, db_column='Roleid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblrole')),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
        migrations.AddField(
            model_name='tblbodyguard',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tbluser'),
        ),
        migrations.CreateModel(
            name='TblWorkSchedule',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('workingdate', models.DateField(blank=True, db_column='WorkingDate', null=True)),
                ('starttime', models.DateTimeField(blank=True, db_column='StartTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='EndTime', null=True)),
                ('shifttype', models.CharField(blank=True, db_column='ShiftType', max_length=10, null=True)),
                ('note', models.TextField(blank=True, db_column='Note', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('contractid', models.ForeignKey(blank=True, db_column='ContractID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblcontract')),
                ('guardid', models.ForeignKey(blank=True, db_column='GuardID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblbodyguard')),
            ],
            options={
                'db_table': 'tbl_work_schedule',
            },
        ),
        migrations.CreateModel(
            name='TblBodyguardEquipment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(blank=True, db_column='StartTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='EndTime', null=True)),
                ('guardid', models.IntegerField(blank=True, db_column='GuardID', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('equipmentid', models.ForeignKey(blank=True, db_column='EquipmentID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblequipment')),
                ('workscheduleid', models.ForeignKey(blank=True, db_column='WorkScheduleID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblworkschedule')),
            ],
            options={
                'db_table': 'tbl_bodyguard_equipment',
            },
        ),
        migrations.CreateModel(
            name='TblCertificateBodyguard',
            fields=[
                ('guardid', models.OneToOneField(db_column='GuardID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bgapp.tblbodyguard')),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('certificateid', models.ForeignKey(db_column='CertificateID', on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblcertificate')),
            ],
            options={
                'db_table': 'tbl_certificate_bodyguard',
                'unique_together': {('guardid', 'certificateid')},
            },
        ),
        migrations.CreateModel(
            name='TblTrainingBodyguard',
            fields=[
                ('trainingid', models.OneToOneField(db_column='TrainingID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bgapp.tbltraining')),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('bodyguardid', models.ForeignKey(db_column='BodyguardID', on_delete=django.db.models.deletion.DO_NOTHING, to='bgapp.tblbodyguard')),
            ],
            options={
                'db_table': 'tbl_training_bodyguard',
                'unique_together': {('trainingid', 'bodyguardid')},
            },
        ),
    ]
