# Generated by Django 5.0.8 on 2024-08-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPayment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=0, max_digits=18, null=True)),
                ('paymentstatus', models.BooleanField(blank=True, db_column='PaymentStatus', null=True)),
                ('details', models.TextField(blank=True, db_column='Details', null=True)),
                ('createat', models.DateTimeField(blank=True, db_column='CreateAt', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
            ],
            options={
                'db_table': 'tbl_Payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTrainingBodyguard',
            fields=[
                ('trainingid', models.OneToOneField(db_column='TrainingID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bgapp.tbltraining')),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
            ],
            options={
                'db_table': 'tbl_training_bodyguard',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='TblBill',
        ),
        migrations.RemoveField(
            model_name='tblbodyguardservice',
            name='guardid',
        ),
        migrations.DeleteModel(
            name='TblCompany',
        ),
        migrations.DeleteModel(
            name='TblContractBodyguardCompany',
        ),
        migrations.DeleteModel(
            name='TblDetailBodyguard',
        ),
        migrations.DeleteModel(
            name='TblDetailCandidate',
        ),
        migrations.DeleteModel(
            name='TblJob',
        ),
        migrations.DeleteModel(
            name='TblNews',
        ),
        migrations.DeleteModel(
            name='TblSkill',
        ),
        migrations.RemoveField(
            model_name='tbltrainingresult',
            name='guardid',
        ),
        migrations.DeleteModel(
            name='TblUserCandidate',
        ),
        migrations.DeleteModel(
            name='TblBodyguardService',
        ),
        migrations.DeleteModel(
            name='TblTrainingResult',
        ),
    ]
